Repository zeit/hyper, pull requests merged in 2018-12, with the labels that each got.

#3255 Update xterm to v3.8.0
  lib/components/style-sheet.js
  lib/components/term.js
  package.json
  yarn.lock
Labels: WIP

#3352 Optimistic session creation
  app/ui/window.js
Labels: 🎨 Type: Enhancement

#3329 Upgrade Electron to v4
  .travis.yml
  app/auto-updater-linux.js
  app/commands.js
  app/index.html
  app/notifications.js
  app/package.json
  app/ui/window.js
  app/yarn.lock
  appveyor.yml
  lib/index.js
  package.json
  yarn.lock
Labels: 🎨 Type: Enhancement

#3336 Performance - Data batching
  app/rpc.js
  app/session.js
  app/ui/window.js
Labels: 📊 Type: Performance
